<!-- DESCRIPTION: Cart Handler for Add, Quantity Update, Remove and Fixing Errors Syntax & Structure
SOURCE: Generated by Gemini AI
DATE: July 22, 2026 -->

<?php
session_start();

if (!isset($_SESSION['cart'])) {
    $_SESSION['cart'] = [];
}

$action = $_POST['action'] ?? $_GET['action'] ?? '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    if ($action === 'add') {
        $item_name = $_POST['item_name'] ?? '';
        $price     = $_POST['price'] ?? '0.00';
        $image     = $_POST['image'] ?? '';
        $quantity  = isset($_POST['quantity']) ? (int)$_POST['quantity'] : 1;
    
    $found = false;
    foreach ($_SESSION['cart'] as &$cart_item) {
        if ($cart_item['name'] === $item_name) {
            $cart_item['quantity'] += $quantity;
            $found = true;
            break;
        }
    }
    unset($cart_item);

    if (!$found) {
        $_SESSION['cart'][] = [
            'name'      => $item_name,
            'price'     => $price,
            'image'     => $image,
            'quantity'  => $quantity
        ];
    }

    header("Location: menu.php?added=1");
    exit();
    }

    if ($action === 'update') {
        $index = isset($_POST['index']) ? (int)$_POST['index'] : -1;
        $change = isset($_POST['change']) ? (int)$_POST['change'] : 0;

        if (isset($_SESSION['cart'][$index])) {
            $_SESSION['cart'][$index]['quantity'] += $change;

            if ($_SESSION['cart'][$index]['quantity'] <= 0) {
                array_splice($_SESSION['cart'], $index, 1);
            }
        }

        header("Location: menu.php?open_cart=1");
        exit();
    }

    if ($action === 'remove') {
        $index = isset($_POST['index']) ? (int)$_POST['index'] : -1;

        if (isset($_SESSION['cart'][$index])) {
            array_splice($_SESSION['cart'], $index, 1);
        }

        header("Location: menu.php?open_cart=1");
        exit();
    }
}
?>