<!-- DESCRIPTION: Checkout Page with Order Checkout Processing and JSON Order Storage
SOURCE: Generated by Gemini AI
DATE: July 24, 2026 -->

<?php
    session_start();

	if (!isset($_SESSION['user'])) {
        $_SESSION['login_message'] = "Please log in to continue proceeding to checkout for your order.";
        header("Location: index.php");
        exit();
    }

    $orders_file = __DIR__ . '/data/orders.json';

    if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['place_order'])) {
        $cart_items = $_SESSION['cart'] ?? [];

        if(!empty($cart_items)) {
            $fullname = trim($_POST['fullname'] ?? '');
            $email = trim($_POST['email'] ?? '');
            $phone = trim($_POST['phone'] ?? '');
            $address = trim($_POST['address'] ?? '');
            $payment_method = trim($_POST['payment_method'] ?? '');

            $subtotal = 0;
            $order_items = [];

            foreach ($cart_items as $item) {
                $item_price = floatval($item['price'] ?? 0);
                $item_qty = intval($item['quantity'] ?? 1);
                $item_total = $item_price * $item_qty;
                $subtotal += $item_total;

                $order_items[] = [
                    'name' => $item['name'] ?? $item['item_name'] ?? 'Unnamed Item',
                    'category' => $item['category'] ?? 'General',
                    'price' => $item_price,
                    'quantity' => $item_qty,
                    'total' => $item_total
                ];
            }

            date_default_timezone_set('Asia/Manila');

            $new_order = [
                'order_id' => 'ORD_' . uniqid(),
                'customer' => [
                    'fullname' => $fullname,
                    'email' => $email,
                    'phone' => $phone,
                    'address' => $address
                ],
                'items' => $order_items,
                'subtotal' => $subtotal,
                'payment_method' => $payment_method,
                'status' => 'Pending',
                'created_at' => date('Y-m-d H:i:s')
            ];

            $existing_orders = [];
            if (file_exists($orders_file)) {
                $data = file_get_contents($orders_file);
                $existing_orders = json_decode($data, true) ?? [];
            }

            array_unshift($existing_orders, $new_order);
            file_put_contents($orders_file, json_encode($existing_orders, JSON_PRETTY_PRINT));

            unset($_SESSION['cart']);

            header("Location: checkout.php?success=1&order_id=" . $new_order['order_id']);
            exit();
        } else {
            header("Location: checkout.php?error=empty_cart");
            exit();
        }
    }

    $cart = $_SESSION['cart'] ?? [];
    $subtotal = 0;
    foreach ($cart as $item) {
        $subtotal += floatval($item['price'] ?? 0) * intval($item['quantity'] ?? 1);
    }
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checkout</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Playfair+Display" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quicksand" />
    <link rel="icon" href="images/logo/favicon_brew-and-shot.png" type="image/x-icon">
    <link rel="stylesheet" href="style.css?v=<?php echo time(); ?>">
</head>
<body>

    <?php
        $page_user = 'user';
    	$page_menu = 'menu';
        include 'header.php';
    ?>

    <div class="container mt-5 p-5 checkout-content shadow-sm">
        <?php if (isset($_GET['success'])) { ?>
            <div class="card border-0 shadow-sm p-4 p-md-5 text-center my-5" style="border-radius: 16px;">
                <div class="mb-3">
                    <i class="bi bi-check-circle-fill text-success" style="font-size: 4rem;"></i>
                </div>
                <h2 class="fw-bold text-dark">Order Placed Successfully!</h2>
                <p class="text-secondary fs-5 mb-2">Thank you for ordering with Brew & Shot.</p>
                <p class="text-muted">Your Order Reference ID is: <strong class="text-dark"><?php echo ($_GET['order_id'] ?? ''); ?></strong></p>
                <div class="mt-4">
                    <a href="menu.php" class="btn btn-brew px-4 py-2 fw-semibold me-2">Back to Menu</a>
                </div>
            </div>
        <?php } else { ?>

            <div class="mb-4">
                <h2 class="fw-bold text-dark mb-1">
                    <i class="bi bi-bag-check-fill accent-text me-2"></i>Checkout
                </h2>
                <p class="text-secondary">Complete your details to place your coffee order.</p>
            </div>

            <?php if (isset($_GET['error']) && $_GET['error'] === 'empty_cart') { ?>
                <div class="alert alert-warning alert-dismissible fade show fw-semibold" role="alert">
                    <i class="bi bi-exclamation-circle-fill me-2"></i>Your cart is empty. Please add items before checking out.
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
            <?php } ?>

            <form action="checkout.php" method="post">
                <div class="row g-4">
                    <div class="col-lg-7">
                        <div class="card border-0 shadow-sm p-4" style="border-radius: 12px;">
                            <h5 class="fw-bold mb-3 text-dark">
                                <i class="bi bi-person-lines-fill me-2 accent-text"></i>Delivery Details
                            </h5>

                            <div class="mb-3">
                                <label for="fullname" class="form-label fw-semibold text-secondary">Full Name</label>
                                <input type="text" class="form-control" id="fullname" name="fullname" placeholder="Your full name" required>
                            </div>

                            <div class="row g-3 mb-3">
                                <div class="col-md-6">
                                    <label for="email" class="form-label fw-semibold text-secondary">Email Address</label>
                                    <input type="email" class="form-control" id="email" name="email" placeholder="Your email address" required>
                                </div>
                                <div class="col-md-6">
                                    <label for="phone" class="form-label fw-semibold text-secondary">Phone Number</label>
                                    <input type="tel" class="form-control" id="phone" name="phone" placeholder="Your phone number" required>
                                </div>
                            </div>

                            <div class="mb-3">
                                <label for="address" class="form-label fw-semibold text-secondary">Delivery Address</label>
                                <textarea class="form-control" id="address" name="address" rows="3" placeholder="House/Unit No., Street, Barangay, City" required></textarea>
                            </div>

                            <h5 class="fw-bold mt-4 mb-3 text-dark">
                                <i class="bi bi-credit-card-fill me-2 accent-text"></i>Payment Method
                            </h5>

                            <div class="form-check p-3 border rounded mb-2">
                                <input class="form-check-input" type="radio" name="payment_method" id="cash" value="Cash" checked>
                                <label class="form-check-label fw-semibold" for="cash">
                                    <i class="bi bi-cash-stack me-2 text-success"></i>Cash
                                </label>
                            </div>

                            <div class="form-check p-3 border rounded">
                                <input class="form-check-input" type="radio" name="payment_method" id="gcash" value="GCash">
                                    <label class="form-check-label fw-semibold" for="gcash">
                                    <i class="bi bi-wallet2 me-2 text-primary"></i>GCash
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-5">
                        <div class="card border-0 shadow-sm p-4" style="border-radius: 12px;">
                            <h5 class="fw-bold mb-3 text-dark">
                                <i class="bi bi-receipt me-2 accent-text"></i>Order Summary
                            </h5>

                            <?php if (!empty($cart)) { ?>
                                <ul class="list-group list-group-flush mb-3">
                                    <?php foreach ($cart as $item) { 
                                        $p = floatval($item['price'] ?? 0);
                                        $q = intval($item['quantity'] ?? 1);    
                                    ?>
                                        <li class="list-group-item d-flex justify-content-between align-items-center px-0 py-2">
                                            <div>
                                                <h6 class="my-0 fw-semibold text-dark"><?php echo ($item['name'] ?? $item['item_name'] ?? 'Item'); ?></h6>
                                                <small class="text-muted">Qty: <?php echo $q; ?> &times; &#8369;<?php echo number_format($p, 2); ?></small>
                                            </div>
                                            <span class="fw-bold text-dark">&#8369;<?php echo number_format($p * $q, 2); ?></span>
                                        </li>
                                    <?php } ?>
                                </ul>

                                <hr class="my-2">

                                <div class="d-flex justify-content-between py-1 text-secondary">
                                    <span>Subtotal</span>
                                    <span class="fw-medium">&#8369;<?php echo number_format($subtotal, 2); ?></span>
                                </div>
                                
                                <hr class="my-2">

                                <button type="submit" name="place_order" class="btn btn-checkout py-3 mt-3 fw-bold shadow-sm d-flex align-items-center justify-content-center gap-2">
                                    <i class="bi bi-bag-check fs-5"></i> Place Order Now
                                </button>
                            <?php } else { ?>
                                <div class="text-center py-4 text-muted">
                                    <i class="bi bi-cart-x fs-1 mb-2 d-block text-secondary"></i>
                                    Your cart is currently empty.
                                    <a href="menu.php" class="d-block mt-3 btn btn-outline-secondary btn-sm">Browse Menu</a>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </form>
        <?php } ?>
    </div>

    <?php
        include 'footer.php';
    ?>

</body>
</html>