//DESCRIPTION: JS Live Clock Script.
//SOURCE: Generated by Gemini AI
//DATE: July 12, 2026

function updateClock() {
    const clockElement = document.getElementById('clock');
    if (!clockElement) return;

    const now = new Date();

    // Options to format the date matching your PHP format: "d M Y | h:i A"
    const dateOptions = {day: '2-digit', month: 'short', year: 'numeric'};
    const timeOptions = {hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: true};

    // Format the date parts
    const dateString = now.toLocaleDateString('en-US', dateOptions);
    const timeString = now.toLocaleTimeString('en-US', timeOptions);

    // Update the navbar text dynamically
    clockElement.textContent = `${dateString} | ${timeString}`;
}

// Run the clock immediately when the page loads
updateClock();

// Refresh the clock every 1 second (1000 milliseconds)
setInterval(updateClock, 1000);