//DESCRIPTION: Quick Auto-Dismiss Enhancement
//SOURCE: Generated by Gemini AI
//DATE: July 25, 2026

document.addEventListener('DOMContentLoaded', function () {
    const loginAlert = document.querySelector('.position-fixed .alert');
    if (loginAlert) {
        setTimeout(function () {
            const bsAlert = new bootstrap.Alert(loginAlert);
            bsAlert.close();
        }, 4000); // Auto-dismisses after 4 seconds
    }
});