<!-- DESCRIPTION: Using a JSON data for both Login & Sign Up.
SOURCE: Generated by Gemini AI
DATE: July 20-21, 2026 -->

<?php
    session_start();

    if ($_SERVER['REQUEST_METHOD'] == 'POST') {
        $email = trim($_POST['email'] ?? '');
        $password = trim($_POST['pswd'] ??'');

        if (empty($email) || empty($password)) {
            header('Location: index.php?empty=1');
            exit();
        }

        $file = __DIR__ . '/data/users.json';
        $users = file_exists($file) ? json_decode(file_get_contents($file), true) : [];

        $user_found = false;
        $logged_in_user = null;

        foreach ($users as $user) {
            if ($user['email'] === $email) {
                if (password_verify($password, $user['password_hash'])) {
                    $user_found = true;
                    $logged_in_user = $user;
                    break;
                }
            }
        }

        if ($user_found) {
            $_SESSION['user'] = $logged_in_user;
        } else {
            header('Location: index.php?invalid=1');
            exit();
        }
    } else {
        if (!isset($_SESSION['user'])) {
            header('Location: index.php');
            exit();
        }
    }
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Playfair+Display" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quicksand" />
    <link rel="icon" href="images/logo/favicon_brew-and-shot.png" type="image/x-icon">
    <link rel="stylesheet" href="style.css?v=<?php echo time(); ?>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>

    <?php
        include 'header.php';
    ?>

    <div class="position-fixed top-0 end-0 p-3" style="z-index: 1080;">
        <div class="alert alert-dismissible fade show shadow-lg border-0 d-flex align-items-center gap-2 m-0" 
            role="alert" 
            style="background-color: #fff8f2; color: #413121; border-radius: 10px;">
            <i class="fa-solid fa-circle-check" style="color: #b78d63;"></i>
            <div>
                <strong>Welcome back, <?php echo ($_SESSION['user']['fullname'] ?? 'Valued Customer'); ?>!</strong> You have successfully logged in.
            </div>
            <button type="button" class="btn-close ms-2" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    </div>
    
    <?php include 'carousel.php' ?>

    <?php include 'menu-promotion.php' ?>

    <?php include 'photo-albums.php' ?>

        <?php
            include 'footer.php';
        ?>

<script src="floating-notif.js"></script>

</body>
</html>