<!-- DESCRIPTION: Sub-Admin Sign-up Form saving to admins.json
SOURCE: Generated by Gemini AI
DATE: July 23, 2026 -->

<?php
    session_start();

    date_default_timezone_set('Asia/Manila');

    $SignUpForm = array("Sign Up","Sub-Administrator");
    $page_subadmin = $page_subadmin ?? 'sub-domain';
?>

<?php
    if ($page_subadmin == 'sub-domain') {
?>

<div class="modal fade" id="addSubAdminModal" tabindex="-1" aria-labelledby="addSubAdminModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fw-bold" id="addSubAdminModalLabel">
                    <?php echo $SignUpForm[1]; ?>
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body p-4">
                <?php
                    if (isset($_GET["empty"])) {
                        echo "<div class='alert alert-warning alert-dismissible fade show fw-semibold mb-3' role='alert'>
                            Please fill in all required fields to register.
                            <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
                            </div>";
                    } elseif (isset($_GET["mismatch"])) {
                        echo "<div class='alert alert-danger alert-dismissible fade show fw-semibold mb-3' role='alert'>
                            Passwords do not match. Please try again.
                            <button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'></button>
                            </div>";
                    }
                ?>   

                <form action="admin-success.php" method="post">
                    <div class="mb-3">          
                        <label for='position' class='form-label'>Position:</label>
                        <select class='form-select' id='position' name='position'>
                            <option disabled selected hidden name='position'>Select your position</option>
                            <?php
                                $position = array("Administrator","Sub-Administrator");    
                                foreach ($position as $pos) {
                                    echo "<option>$pos</option>";
                                }
                            ?>
                        </select>
                    </div>

                    <div class="row">
                        <div class="col-lg-6 mb-3">
                            <label for="fullname" class="form-label">Full Name:</label>
                            <input type="text" class="form-control" id="fullname" placeholder="Enter full name" name="fullname">
                        </div>
                        <div class="col-lg-6 mb-3">
                            <label for="email" class="form-label">Email Address:</label>
                            <input type="email" class="form-control" id="email" placeholder="Enter email address" name="email">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="mb-3">
                                <label for="gender" class="form-label">Gender:</label>
                                <select class="form-select" id="gender" name="gender">
                                    <option disabled selected hidden name="gender">Select your gender</option>
                                    <?php
                                        $genders = array("Male", "Female", "Other", "Prefer not to say");
                                        foreach ($genders as $gender) {
                                            echo "<option>$gender</option>";
                                        }
                                    ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="mb-3">
                                <label for="country" class="form-label">Country:</label>
                                <select class="form-select" id="country" name="country">
                                    <option disabled selected hidden name="country">Select your country</option>
                                    <?php
                                        $countries = array("Argentina", "Australia", "Austria", "Bangladesh", "Belgium", "Bhutan", "Brazil", "Canada", "Chile", "China", "Colombia", "Czech Republic", "Denmark", "Egypt", "Finland", "France", "Germany", "Greece", "Hungary", "India", "Indonesia", "Ireland", "Israel", "Italy", "Japan", "Kenya", "Malaysia", "Maldives", "Mexico", "Nepal", "Netherlands", "New Zealand", "Nigeria", "Norway", "Pakistan", "Peru", "Philippines", "Poland", "Portugal", "Russia", "Saudi Arabia", "Singapore", "South Africa", "South Korea", "Spain", "Sri Lanka", "Sweden", "Switzerland", "Thailand", "Turkey", "United Arab Emirates", "United Kingdom", "United States", "Venezuela", "Vietnam");
                                        foreach ($countries as $country) {       
                                            echo "<option>$country</option>";
                                        }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="home" class="form-label">Home Address:</label>
                        <input type="text" class="form-control" id="home" placeholder="Enter home address" name="home">
                    </div>
                    <div class="row">
                        <label for="dob" class="form-label">Date of Birth:</label>
                        <div class="col-lg-4 mb-3">
                            <select class="form-select form-label" id="dob_month" name="dob_month">
                                <option disabled selected hidden name="dob_month">Month</option>
                                <?php
                                    $months = array("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December");
                                    foreach ($months as $month) {
                                        echo "<option>$month</option>";
                                    }
                                ?>
                            </select>
                        </div>
                        <div class="col-lg-4 mb-3">
                            <select class="form-select form-label" id="dob_day" name="dob_day">
                                <option disabled selected hidden name="dob_day">Day</option>
                                <?php
                                    for ($d = 1; $d <= 31; $d++) {
                                        echo "<option>$d</option>";
                                    }
                                ?>
                            </select>
                        </div>
                        <div class="col-lg-4 mb-3">
                            <select class="form-select form-label" id="dob_year" name="dob_year">
                                <option disabled selected hidden name="dob_year">Year</option>
                                <?php
                                    $year = date("Y");

                                    for ($y = $year; $y >= 1950; $y--) {
                                        echo "<option>$y</option>";
                                    }
                                ?>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="mb-3">
                                <label for="graduate" class="form-label">Graduate School:</label>
                                <input type="text" class="form-control" id="graduate" placeholder="Enter graduate school" name="graduate">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="mb-3">
                                <label for="edulvl" class="form-label">Education Level</label>
                                <select class="form-select" id="edulvl" name="edulvl">
                                    <option disabled selected hidden name="edulvl">Select your education level</option>
                                    <?php
                                        $educationLevels = array("High School", "Vocational", "Associate Degree", "Bachelor's Degree", "Master's Degree", "Doctorate");
                                        foreach ($educationLevels as $edulvl) {
                                            echo "<option>$edulvl</option>";
                                        }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="username" class="form-label">Username:</label>
                        <input type="text" class="form-control" id="username" placeholder="Enter username" name="username">
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="mb-3">
                                <label for="pwd" class="form-label">Password:</label>
                                <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="mb-3">
                                <label for="confirm_pwd" class="form-label">Confirm Password:</label>
                                <input type="password" class="form-control" id="confirm_pwd" placeholder="Confirm password" name="confirm_pswd">
                            </div>
                        </div>
                    </div>
                    <div class="form-check mb-3">
                        <label class="form-check-label">
                            <input class="form-check-input" type="checkbox"> I agree to the <a href="#" class="text-decoration-none">Terms and Conditions</a>.
                        </label>
                    </div>

                    <div class="modal-footer px-0 pb-0 pt-3">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-sub-admin">Sign Up</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php } else { ?>

<div class="signup-form p-4">
    <h2 class="fw-bold mb-3"> <?php echo $SignUpForm[0] ?> </h2>
    <form action="success.php" method="post">
        <?php
            if (isset($_GET["empty"])) {
                echo "<div class='alert alert-warning'>
                    Please fill in all fields to log in.
                    </div>";
            } elseif (isset($_GET["mismatch"])) {
                echo "<div class='alert alert-danger'>
                    Passwords do not match. Please try again.
                    </div>";
            }
        ?>

        <div class="row">
            <div class="col-lg-6">
                <div class="mb-3">
                    <label for="fullname" class="form-label">Full Name:</label>
                    <input type="text" class="form-control" id="fullname" placeholder="Enter full name" name="fullname">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="mb-3">
                    <label for="email" class="form-label">Email Address:</label>
                    <input type="email" class="form-control" id="email" placeholder="Enter email address" name="email">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="mb-3">
                    <label for="gender" class="form-label">Gender:</label>
                    <select class="form-select" id="gender" name="gender">
                        <option disabled selected hidden name="gender">Select your gender</option>
                        <?php
                            $genders = array("Male", "Female", "Other", "Prefer not to say");
                            foreach ($genders as $gender) {
                                echo "<option>$gender</option>";
                            }
                        ?>
                    </select>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="mb-3">
                    <label for="country" class="form-label">Country:</label>
                    <select class="form-select" id="country" name="country">
                        <option disabled selected hidden name="country">Select your country</option>
                        <?php
                            $countries = array("Argentina", "Australia", "Austria", "Bangladesh", "Belgium", "Bhutan", "Brazil", "Canada", "Chile", "China", "Colombia", "Czech Republic", "Denmark", "Egypt", "Finland", "France", "Germany", "Greece", "Hungary", "India", "Indonesia", "Ireland", "Israel", "Italy", "Japan", "Kenya", "Malaysia", "Maldives", "Mexico", "Nepal", "Netherlands", "New Zealand", "Nigeria", "Norway", "Pakistan", "Peru", "Philippines", "Poland", "Portugal", "Russia", "Saudi Arabia", "Singapore", "South Africa", "South Korea", "Spain", "Sri Lanka", "Sweden", "Switzerland", "Thailand", "Turkey", "United Arab Emirates", "United Kingdom", "United States", "Venezuela", "Vietnam");
                            foreach ($countries as $country) {
                                echo "<option>$country</option>";
                            }
                        ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="mb-3">
            <label for="home" class="form-label">Home Address:</label>
            <input type="text" class="form-control" id="home" placeholder="Enter home address" name="home">
        </div>
        <div class="row">
            <label for="dob" class="form-label">Date of Birth:</label>
            <div class="col-lg-4 mb-3">
                <select class="form-select form-label" id="dob_month" name="dob_month">
                    <option disabled selected hidden name="dob_month">Month</option>
                    <?php
                        $months = array("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December");
                        foreach ($months as $month) {
                            echo "<option>$month</option>";
                        }
                    ?>
                </select>
            </div>
            <div class="col-lg-4 mb-3">
                <select class="form-select form-label" id="dob_day" name="dob_day">
                    <option disabled selected hidden name="dob_day">Day</option>
                    <?php
                        for ($d = 1; $d <= 31; $d++) {
                            echo "<option>$d</option>";
                        }
                    ?>
                </select>
            </div>
            <div class="col-lg-4 mb-3">
                <select class="form-select form-label" id="dob_year" name="dob_year">
                    <option disabled selected hidden name="dob_year">Year</option>
                    <?php
                        $year = date("Y");

                        for ($y = $year; $y >= 1950; $y--) {
                            echo "<option>$y</option>";
                        }
                    ?>
                </select>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="mb-3">
                    <label for="graduate" class="form-label">Graduate School:</label>
                    <input type="text" class="form-control" id="graduate" placeholder="Enter graduate school" name="graduate">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="mb-3">
                    <label for="edulvl" class="form-label">Education Level</label>
                    <select class="form-select" id="edulvl" name="edulvl">
                        <option disabled selected hidden name="edulvl">Select your education level</option>
                        <?php
                            $educationLevels = array("High School", "Vocational", "Associate Degree", "Bachelor's Degree", "Master's Degree", "Doctorate");
                            foreach ($educationLevels as $edulvl) {
                                echo "<option>$edulvl</option>";
                            }
                        ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="mb-3">
            <label for="username" class="form-label">Username:</label>
            <input type="text" class="form-control" id="username" placeholder="Enter username" name="username">
        </div>
        <div class="row">
            <div class="col-lg-6">
                <div class="mb-3">
                    <label for="pwd" class="form-label">Password:</label>
                    <input type="password" class="form-control" id="pwd" placeholder="Enter password" name="pswd">
                </div>
            </div>
            <div class="col-lg-6">
                <div class="mb-3">
                    <label for="confirm_pwd" class="form-label">Confirm Password:</label>
                    <input type="password" class="form-control" id="confirm_pwd" placeholder="Confirm password" name="confirm_pswd">
                </div>
            </div>
        </div>
        <div class="form-check mb-3">
            <label class="form-check-label">
                <input class="form-check-input" type="checkbox"> I agree to the <a href="#" class="text-decoration-none">Terms and Conditions</a>.
            </label>
        </div>
        <button type="submit" class="btn btn-primary">Sign Up</button>
        <hr>
        <p class="text-center">Already have an account? <a href="index.php" class="text-decoration-underline">Login</a>.</p>
    </form>
</div>

<?php } ?>