<!-- DESCRIPTION: Fixing Errors Syntax & Structure and Using a JSON data for Upload Image.
SOURCE: W3Schools Library and Generated by Gemini AI
DATE: July 21, 2026 -->

<?php
date_default_timezone_set('Asia/Manila');

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $item_name = trim($_POST['item_name'] ?? '');
    $category  = trim($_POST['category'] ?? '');
    $price     = (float)($_POST['price'] ?? 0);

    if (empty($item_name) || empty($category) || $price <= 0) {
        header('Location: admin/menu-items.php?empty=1');
        exit();
    }

    if (!isset($_FILES["image"]) || $_FILES["image"]["error"] !== UPLOAD_ERR_OK) {
        header('Location: admin/menu-items.php?empty=1');
        exit();
    }

    $target_dir = __DIR__ . '/uploads/';

    if (!is_dir($target_dir)) {
        mkdir($target_dir, 0777, true);
    }

    $file_name     = basename($_FILES["image"]["name"]);
    $target_file   = $target_dir . $file_name;
    $uploadOk      = 1;
    $imageFileType = strtolower(pathinfo($target_file, PATHINFO_EXTENSION));

    $check = getimagesize($_FILES["image"]["tmp_name"]);
    if ($check === false) {
        echo "<div class='alert alert-warning'>File is not an image.</div>";
        $uploadOk = 0;
    }

    if (file_exists($target_file)) {
        echo "<div class='alert alert-warning'>Sorry, file already exists.</div>";
        $uploadOk = 0;
    }

    if ($_FILES["image"]["size"] > 5000000) {
        echo "<div class='alert alert-warning'>Sorry, your file is too large (max 5MB).</div>";
        $uploadOk = 0;
    }

    $allowed_types = ["jpg", "jpeg", "png", "webp"];
    if (!in_array($imageFileType, $allowed_types)) {
        echo "<div class='alert alert-warning'>Sorry, only JPG, JPEG, PNG & WEBP files are allowed.</div>";
        $uploadOk = 0;
    }

    if ($uploadOk == 1) {
        if (move_uploaded_file($_FILES["image"]["tmp_name"], $target_file)) {

            $items_file = 'data/items.json';
            $current_items = file_exists($items_file) ? json_decode(file_get_contents($items_file), true) : [];

            if (!is_array($current_items)) {
                $current_items = [];
            }

            $new_item = [
                "id"         => uniqid('prod_'),
                "name"       => $item_name,
                "category"   => $category,
                "price"      => number_format($price, 2, '.', ''),
                "image_url"  => 'uploads/' . $file_name,
                "created_at" => date("Y-m-d H:i:s")
            ];

            $current_items[] = $new_item;

            file_put_contents($items_file, json_encode($current_items, JSON_PRETTY_PRINT));

            header('Location: admin/menu-items.php?success=1');
            exit();
        } else {
            echo "<div class='alert alert-warning'>Sorry, there was an error moving your uploaded file.</div>";
        }
    }
}
?>