<!-- DESCRIPTION: Sub-Admin Creation Success Confirmation Page
SOURCE: Generated by Gemini AI
DATE: July 23, 2026 -->

<?php 
    if($_SERVER['REQUEST_METHOD'] === 'POST') {
        $position = trim($_POST['position'] ?? '');
        $full_name = trim($_POST['fullname'] ?? '');
        $email = trim($_POST['email'] ?? '');
        $gender = trim($_POST['gender'] ?? '');
        $country = trim($_POST['country'] ?? '');
        $home_address = trim($_POST['home'] ?? '');
        $dob_month = trim($_POST['dob_month'] ?? '');
        $dob_day = trim($_POST['dob_day'] ?? '');
        $dob_year = trim($_POST['dob_year'] ?? '');
        $graduate_school = trim($_POST['graduate'] ?? '');
        $education_level = trim($_POST['edulvl'] ?? '');
        $username = trim($_POST['username'] ?? '');
        $password = trim($_POST['pswd'] ?? '');
        $confirm_password = trim($_POST['confirm_pswd'] ?? '');

        if (empty($position) || empty($full_name) || empty($email) || empty($gender) || empty($country) || empty($home_address) || empty($dob_month) || empty($dob_day) || empty($dob_year) || empty($graduate_school) || empty($education_level) || empty($username) || empty($password) || empty($confirm_password)) {
            header('Location: sub-admin.php?empty=1');
            exit();
        } elseif ($password !== $confirm_password) {
            header('Location: sub-admin.php?mismatch=1');
            exit();
        }

        $dob = ($dob_month && $dob_day && $dob_year) ? "$dob_month $dob_day, $dob_year" : 'N/A';

        $file = __DIR__ . '/../data/admins.json';

        if (!file_exists(__DIR__ . '/../data')) {
            mkdir(__DIR__ . '/../data', 0777, true);
        }

        $json_contents = file_exists($file) ? file_get_contents($file) : '[]';
        $current_data = json_decode($json_contents, true);

        if (!is_array($current_data)) {
            $current_data = [];
        }

        date_default_timezone_set('Asia/Manila');

        $new_admin = array(
            "id"                => uniqid('adm_'),
            "position"          => $position,
            "role"              => ($position === 'Sub-Administrator') ? 'sub_admin' : 'admin',
            "fullname"          => $full_name,
            "email"             => $email,
            "gender"            => $gender,
            "country"           => $country,
            "home_address"      => $home_address,
            "dob"               => $dob,
            "graduate_school"   => !empty($graduate_school) ? $graduate_school : 'N/A',
            "education_level"   => $education_level,
            "username"          => $username,
            "password_hash"     => password_hash($password, PASSWORD_DEFAULT),
            "created_at"        => date("Y-m-d H:i:s")
        );

        $current_data[] = $new_admin;
        $json_string = json_encode($current_data, JSON_PRETTY_PRINT);

        if (file_put_contents($file, $json_string) === false) {
            die("ERROR: Unable to write to 'admins.json'. Please check file write permissions or path!");
        }
    
        $user_details = array(
            "Position"        => $position,
            "Full Name"       => $full_name,
            "Email Address"   => $email,
            "Gender"          => $gender,
            "Country"         => $country,
            "Home Address"    => $home_address,
            "Date of Birth"   => $dob,
            "Graduate School" => $graduate_school,
            "Education Level" => $education_level,
            "Username"        => $username
        );
    } else {
        header('Location: sub-admin.php');
        exit();
    }
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Success</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Playfair+Display" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quicksand" />
    <link rel="icon" href="../images/logo/favicon_brew-and-shot.png" type="image/x-icon">
    <link rel="stylesheet" href="../style.css?v=<?php echo time(); ?>">
</head>
<body>

    <?php
        $page_adminsuccess = 'admin success';
        include '../header.php';
    ?>

    <div class="container" style="max-width: 900px;">
        <div class="text-center border-0 shadow-sm align-items-center">
            <?php 
                echo "<div class='alert alert-success'>
                You have successfully registered a new Administrator! Please <a href='index.php' class='text-decoration-underline'>Admin Login</a> to continue.
                </div>";
            ?>
        </div>

        <div class="user_details-form p-4 bg-white rounded shadow-sm">
            <h2 class="fw-bold mb-4">Admin Registration Details</h2>
            <div class="table-responsive">
                <table class="table table-striped">
                    <tbody>
                        <?php foreach ($user_details as $label => $value) { ?>
                            <tr class="lh-base">
                                <th style="width: 35%;"><?php echo $label; ?>:</th>
                                <td><?php echo $value; ?></td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
            <div class="mt-4 text-end">
                <a href="sub-admin.php" class="btn btn-sub-admin">View All Sub-Admins</a>
            </div>
        </div>
    </div>

    <?php
        include '../footer.php';
    ?>
    
</body>
</html>