<!-- DESCRIPTION: Using a JSON data for both Login & Sign Up with Real-time Order Analytics
SOURCE: Generated by Gemini AI
DATE: July 21 and 24, 2026 -->

<?php
    session_start();

    if ($_SERVER['REQUEST_METHOD'] === 'POST') {
        $email = trim($_POST['email'] ?? '');
        $password = trim($_POST['pswd'] ??'');
        $position = trim($_POST['position'] ?? '');
    
        if (empty($email) || empty($password) || empty($position)) {
            header('Location: index.php?empty=1');
            exit();
        }

        $file = __DIR__ . '/../data/admins.json';
        $admins = file_exists($file) ? json_decode(file_get_contents($file), true) : [];

        $admin_found = false;
        $logged_in_admin = null;

        if (is_array($admins)) {
            foreach ($admins as $admin) {
                if ($admin['email'] === $email && $admin['position'] === $position) {
                    if (password_verify($password, $admin['password_hash'])) {
                        $admin_found = true;
                        $logged_in_admin = $admin;
                        break;
                    }
                }
            }
        }

        if ($admin_found) {
            $_SESSION['admin'] = $logged_in_admin;
            header('Location: dashboard.php');
            exit();
        } else {
            header('Location: index.php?invalid=1');
            exit();
        }
    } else {
        if (!isset($_SESSION['admin'])) {
            header('Location: index.php');
            exit();
        }
    }

    $orders_file = __DIR__ . '/../data/orders.json';
    $admins_file = __DIR__ . '/../data/admins.json';
    $items_file = __DIR__ . '/../data/items.json';

    $orders = file_exists($orders_file) ? (json_decode(file_get_contents($orders_file), true) ?? []) : [];
    $admins = file_exists($admins_file) ? (json_decode(file_get_contents($admins_file), true) ?? []) : [];
    $items = file_exists($items_file) ? (json_decode(file_get_contents($items_file), true) ?? []) : [];

    $total_orders = count($orders);
    $total_revenue = 0;
    $pending_orders = 0;

    foreach ($orders as $order) {
        $total_revenue += floatval($order['subtotal'] ?? 0);
        if (strtolower($order['status'] ?? '') === 'pending') {
            $pending_orders++;
        } 
    }

    $total_subadmins = count(array_filter($admins, function($admin) {
        $role = strtolower($admin['role'] ?? $admin['position'] ?? '');
        return str_contains($role, 'sub');
    }));

    $total_menu_items = count($items);
    $recent_orders = array_slice($orders, 0, 5);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Playfair+Display" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quicksand" />
    <link rel="icon" href="../images/logo/favicon_brew-and-shot.png" type="image/x-icon">
    <link rel="stylesheet" href="../style.css?v=<?php echo time(); ?>">
</head>
<body>

    <?php
        $page_dashboard = 'dashboard';
        include '../sidebar-menu.php';
    ?>

    <div class="main-page-content">
        <div class="welcome-card shadow-sm p-4 rounded-3 border-0 mb-4">
            <div class="d-flex align-items-center gap-3">
                <h2 class="fw-bold mb-1 welcome-title">
                    Welcome back, <?php echo $_SESSION['admin']['fullname'] ?? 'Valued Admin'; ?>!
                </h2>
                <p class="text-muted mb-0 welcome-subtitle">
                    Position: <?php echo $_SESSION['admin']['position'] ?? 'Admin'; ?>
                </p> 
            </div>
        </div>

        <div class="row g-3 mb-4">
            <div class="col-12 col-sm-6 col-lg-3">
                <div class="card stat-card shadow-sm p-3 h-100">
                    <div class="d-flex align-items-center justify-content-between">
                        <div>
                            <span class="text-secondary small fw-semibold text-uppercase">Total Sales</span>
                            <h3 class="fw-bold text-dark mt-1 mb-0">&#8369;<?php echo number_format($total_revenue, 2); ?></h3>
                        </div>
                        <div class="icon-box bg-success-subtle text-success">
                            <i class="bi bi-currency-dollar"></i>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-12 col-sm-6 col-lg-3">
                <div class="card stat-card shadow-sm p-3 h-100">
                    <div class="d-flex align-items-center justify-content-between">
                        <div>
                            <span class="text-secondary small fw-semibold text-uppercase">Total Orders</span>
                            <h3 class="fw-bold text-dark mt-1 mb-0"><?php echo $total_orders; ?></h3>
                            <?php if ($pending_orders > 0) { ?>
                                <small class="text-warning fw-semibold"><?php echo $pending_orders; ?> pending</small>
                            <?php } ?>
                        </div>
                        <div class="icon-box bg-primary-subtle text-primary">
                            <i class="bi bi-bag-check-fill"></i>
                        </div>
                    </div>
                </div>
            </div>

        <div class="col-12 col-sm-6 col-lg-3">
            <div class="card stat-card shadow-sm p-3 h-100">
                <div class="d-flex align-items-center justify-content-between">
                    <div>
                        <span class="text-secondary small fw-semibold text-uppercase">Menu Items</span>
                        <h3 class="fw-bold text-dark mt-1 mb-0"><?php echo $total_menu_items; ?></h3>
                    </div>
                    <div class="icon-box bg-warning-subtle text-warning">
                        <i class="bi bi-cup-hot-fill"></i>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12 col-sm-6 col-lg-3">
            <div class="card stat-card shadow-sm p-3 h-100">
                <div class="d-flex align-items-center justify-content-between">
                    <div>
                        <span class="text-secondary small fw-semibold text-uppercase">Sub-Admins</span>
                        <h3 class="fw-bold text-dark mt-1 mb-0"><?php echo $total_subadmins; ?></h3>
                    </div>
                    <div class="icon-box bg-info-subtle text-info">
                        <i class="bi bi-people-fill"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

        <div class="card border-0 shadow-sm p-3 p-md-4 mb-4" style="border-radius: 14px;">
            <div class="d-flex align-items-center justify-content-between mb-3">
                <h5 class="fw-bold text-dark mb-0">
                    <i class="bi bi-clock-history me-2 text-brew"></i>Recent Orders
                </h5>
                <span class="badge bg-brew-light text-brew px-3 py-2 fw-medium">Latest <?php echo count($recent_orders); ?></span>
            </div>

            <?php if(empty($recent_orders)) { ?>
                <div class="text-center py-5 text-muted">
                    <i class="bi bi-inbox fs-1 d-block mb-2 text-secondary"></i>
                    No orders recorded yet.
                </div>
            <?php } else { ?>
                <div class="table-responsive">
                    <table class="table table-hover align-middle mb-0 text-nowrap">
                        <thead class="table-light">
                            <tr>
                                <th>Order ID</th>
                                <th>Customer</th>
                                <th>Payment</th>
                                <th>Total</th>
                                <th>Status</th>
                                <th>Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($recent_orders as $order) { 
                                $status = strtolower($order['status'] ?? 'pending');
                                $badge_class = match($status) {
                                    'completed' => 'bg-success',
                                    'cancelled' => 'bg-danger',
                                    'processing' => 'bg-info',
                                    default => 'bg-warning text-dark',
                                };
                            ?>
                                <tr>
                                    <td class="fw-bold text-primary"><code><?php echo($order['order_id'] ?? 'N/A'); ?></code></td>
                                    <td class="fw-semibold text-dark">
                                        <?php echo ($order['customer']['fullname'] ?? 'Guest'); ?>
                                        <br><small class="text-muted"><?php echo ($order['customer']['phone'] ?? ''); ?></small>
                                    </td>
                                    <td>
                                        <span class="badge bg-light text-dark border">
                                            <?php echo ($order['payment_method'] ?? 'Cash'); ?>
                                        </span>
                                    </td>
                                    <td class="fw-bold text-dark">&#8369;<?php echo number_format(floatval($order['subtotal'] ?? 0), 2); ?></td>
                                    <td>
                                        <span class="badge rounded-pill <?php echo $badge_class; ?> px-3 py-2">
                                            <?php echo ucfirst($status); ?>
                                        </span>
                                    </td>
                                    <td class="text-muted small"><?php echo ($order['created_at'] ?? 'N/A'); ?></td>
                                </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            <?php } ?>
        </div>

        <?php
            $page_adminfooter = 'admin footer';
            include '../footer.php';
        ?>

    </div>

</body>
</html>