<!-- DESCRIPTION: Menu Items Display Script with Category Filter, Category Grouped and Fixing Errors Syntax & Structure
SOURCE: Generated by Gemini AI
DATE: July 21-22, 2026 -->

<?php
$is_admin = (strpos($_SERVER['SCRIPT_NAME'], '/admin/') !== false);
$json_path = __DIR__ . '/../data/items.json';

$selected_category = $_GET['cat'] ?? 'All';  

if (file_exists($json_path)) {
    $json_content = file_get_contents($json_path);
    $items_data = json_decode($json_content, true);

    if (!empty($items_data) && is_array($items_data)) {

        $grouped_items = [];
        foreach ($items_data as $item) {
            $cat_name = trim($item['category'] ?? 'Uncategorized');
            $grouped_items[$cat_name][] = $item;
        }

        ksort($grouped_items);

        $has_rendered_items = false;

        foreach ($grouped_items as $category_title => $items) {
            if ($selected_category !== 'All' && strcasecmp(trim($category_title), trim($selected_category)) !== 0) {
                continue;
            }

            $has_rendered_items = true;
            ?>

            <div class="col-12 mt-4">
                <h2 class="fw-bold text-dark px-2"><?php echo $category_title; ?></h2>
           		<hr>
            </div>

            <?php
            foreach ($items as $item) {
                $item_name = $item['name'] ?? 'Unnamed Item';
                $price     = $item['price'] ?? '0.00';

                $raw_filename   = $item['image_url'] ?? '';
                $clean_filename = ltrim(str_replace('../', '', $raw_filename), '/');

                $image_path = $is_admin ? '../' . $clean_filename : $clean_filename;
                ?>
            
                <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                    <div class="card h-100 border-0 shadow-sm overflow-hidden">
                        <img src="<?php echo $image_path; ?>" class="card-img-top" alt="<?php echo $item_name; ?>" style="height: 200px; object-fit: cover;">
                        <div class="card-body d-flex flex-column justify-content-between p-3">
                            <div>
                                <h5 class="card-title fw-bold mb-1"><?php echo $item_name; ?></h5>
                            </div>
                            <div class="mt-3">
                                <div class="d-flex align-items-center justify-content-between gap-2">
                                    <p class="card-text fw-bold fs-5 text-dark mb-0">&#8369;<?php echo $price; ?></p>   
                                </div>

                                <div class="mt-3">
                                    <?php if (!$is_admin) { ?>
                                        <form action="cart.php" method="post" class="m-0">
                                            <input type="hidden" name="action" value="add">
                                            <input type="hidden" name="item_name" value="<?php echo $item_name; ?>">
                                            <input type="hidden" name="price" value="<?php echo $price; ?>">
                                            <input type="hidden" name="image" value="<?php echo $image_path; ?>">

                                            <div class="row g-2 align-items-end">
                                                <div class="col-6">
                                                    <label for="qty_<?php echo md5($item_name); ?>" class="form-label small text-muted mb-2 fw-semibold">Quantity</label>
                                                    <select name="quantity" id="qty_<?php echo md5($item_name); ?>" class="form-select form-select-sm border-secondary-subtle">
                                                        <?php
                                                            for ($qty = 1; $qty <=5; $qty++) {
                                                                echo "<option value='$qty'>$qty</option>";
                                                            }
                                                        ?>
                                                    </select>
                                                </div>
                                                <div class="col-6">
                                                    <button type="submit" class="btn btn-sm fw-semibold btn-cart">
                                                        <i class="bi bi-cart-plus me-1"></i> Add
                                                    </button>
                                                </div>
                                            </div>
                                        </form>
                                    <?php } ?>
                                </div>    
                            </div>
                        </div>
                    </div>
                </div>
                <?php
            }
        }

        if (!$has_rendered_items) {
            echo '<div class="col-12"><div class="alert alert-info">No menu items found in this category.</div></div>';
        }
    } else {
        echo '<div class="col-12"><div class="alert alert-info">No menu items found. Add some in the Admin Panel!</div></div>';
    } 
} else {
    echo '<div class="col-12"><div class="alert alert-warning">Could not load menu data.</div></div>';
}
?>