<!-- DESCRIPTION: Sub-Admin Accounts Management & Inline Deletion
SOURCE: Generated by Gemini AI
DATE: July 23, 2026 -->

<?php
session_start();

$admins_file = __DIR__ . '/../data/admins.json';

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'delete_sub_admin') {
    $target_id = $_POST['id'] ?? '';
    $target_username = $_POST['username'] ?? '';

    if (file_exists($admins_file)) {
        $data = file_get_contents($admins_file);
        $all_data = json_decode($data, true) ?? [];

        $updated_data = array_filter($all_data, function($admin) use ($target_id, $target_username) {
            if (!empty($target_id) && isset($admin['id'])) {
                return $admin['id'] !== $target_id;
            }
            return ($admin['username'] ?? '') !== $target_username;
        });

        file_put_contents($admins_file, json_encode(array_values($updated_data), JSON_PRETTY_PRINT));
    }

    header("Location: sub-admin.php?deleted=1");
    exit();
}

$all_admins = [];
if (file_exists($admins_file)) {
    $json_data = file_get_contents($admins_file);
    $all_admins = json_decode($json_data, true) ?? [];
}

$sub_admins = array_filter($all_admins, function($admin) {
    $role = strtolower($admin['role'] ?? $admin['position'] ?? '');
    return str_contains($role, 'sub');
});

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sub Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Playfair+Display" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Quicksand" />
    <link rel="icon" href="../images/logo/favicon_brew-and-shot.png" type="image/x-icon">
    <link rel="stylesheet" href="../style.css?v=<?php echo time(); ?>">
</head>
<body>

    <?php
        $page_subadmin = 'sub-admin';
        include '../sidebar-menu.php';
    ?>

    <div class="main-page-content">

        <div class="container p-5 sub-admin-content shadow-sm">

            <?php if (isset($_GET['deleted'])) { ?>
                <div class="alert alert-success alert-dismissible fade show fw-semibold mb-4" role="alert">
                    <i class="bi bi-check-circle-fill me-2"></i>Sub-admin account successfully deleted.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            <?php } ?>

            <div class="d-flex flex-column flex-sm-row align-items-start align-items-sm-center justify-content-between gap-3 mb-4">
                <div>
                    <h2 class="fw-bold text-dark mb-1">
                        <i class="bi bi-person-gear me-2"></i>Sub-Admin Accounts
                    </h2>
                    <p class="text-secondary mb-0">Manage staff and secondary administrative accounts</p>
                </div>
                <button type="button" class="btn btn-sub-admin px-4 py-2 fw-semibold shadow-sm text-nowrap" data-bs-toggle="modal" data-bs-target="#addSubAdminModal">
                    <i class="bi bi-person-plus-fill me-2"></i>Add Sub-Admin
                </button>
            </div>

            <div class="card border-0 shadow-sm p-3 p-md-4" style="border-radius: 12px;">
                <?php if (empty($sub_admins)) { ?>
                    <div class="text-center py-5">
                        <i class="bi bi-person-gear text-muted mb-3" style="font-size: 3rem;"></i>
                        <h5 class="fw-bold text-dark">No Sub-Admins Found</h5>
                        <p class="text-secondary mb-3">You haven't registered any sub-admin accounts in <code>admins.json</code> yet.</p>
                        <button type="button" class="btn btn-sub-admin btn-sm px-3" data-bs-toggle="modal" data-bs-target="#addSubAdminModal">Create One Now</button>
                    </div>
                <?php } else { ?>
                    <div class="table-responsive">
                        <table class="table table-hover align-middle mb-0 text-nowrap">
                            <thead class="table-light">
                                <tr>
                                    <th>Name</th>
                                    <th>Username</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                    <th>Created Date</th>
                                    <th class="text-center">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($sub_admins as $admin) { 
                                    $modal_id = "deleteModal_" . md5($admin['id'] ?? $admin['username']);    
                                ?>
                                    <tr>
                                        <td class="fw-bold text-dark">
                                            <i class="bi bi-person-circle text-secondary me-2"></i>
                                            <?php echo($admin['fullname'] ?? $admin['username']); ?>
                                        </td>
                                        <td><code><?php echo($admin['username']); ?></code></td>
                                        <td><?php echo($admin['email']); ?></td>
                                        <td>
                                            <span class="badge rounded-pill bg-secondary px-3 py-2">Sub-Admin</span>
                                        </td>
                                        <td class="text-muted small"><?php echo($admin['created_at'] ?? 'N/A'); ?></td>
                                        <td class="text-center">
                                            <button type="button" class="btn btn-outline-danger btn-sm px-3" data-bs-toggle="modal" data-bs-target="#<?php echo $modal_id; ?>">
                                                <i class="bi bi-trash3-fill me-1"></i> Delete
                                            </button>

                                            <div class="modal fade text-start" id="<?php echo $modal_id; ?>" tabindex="-1" aria-hidden="true">
                                                <div class="modal-dialog modal-dialog-centered">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title fw-bold text-danger">
                                                                <i class="bi bi-exclamation-triangle-fill me-2"></i>Delete Sub-Admin
                                                            </h5>
                                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                        </div>
                                                        <div class="modal-body py-4">
                                                            Are you sure you want to delete account for 
                                                            <strong><?php echo ($admin['fullname'] ?? $admin['username']); ?></strong>?
                                                        </div>
                                                        <div class="modal-footer">
                                                            <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                                                            <form action="sub-admin.php" method="POST" class="d-inline">
                                                                <input type="hidden" name="action" value="delete_sub_admin">
                                                                <input type="hidden" name="id" value="<?php echo ($admin['id'] ?? ''); ?>">
                                                                <input type="hidden" name="username" value="<?php echo ($admin['username'] ?? ''); ?>">
                                                                <button type="submit" class="btn btn-danger px-4">Confirm Delete</button>
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>
                <?php } ?>
            </div>
        </div>

        <?php 
            $page_subadmin = 'sub-domain';
            include '../signup-form.php'; 
        ?>

        <?php
            $page_adminfooter = 'admin footer';
            include '../footer.php';
        ?>

    </div>

    <script src="modal-auto-open.js"></script>

</body>
</html>